//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 1.102.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Volo.Abp.Localization;
using FS.Abp.SettingManagement.Localization;

namespace FS.Abp.SettingManagement.Core
{
    public class CorePermissionDefinitionProvider : Volo.Abp.Authorization.Permissions.PermissionDefinitionProvider
    {
        public override void Define(Volo.Abp.Authorization.Permissions.IPermissionDefinitionContext context)
        {
            var CoreGroup = context.AddGroup(CorePermissionNames.GroupName);

            var DevelopPage = CoreGroup.AddPermission(CorePermissionNames.DevelopPage.Default);
            DevelopPage.AddChild(CorePermissionNames.DevelopPage.Create);
            DevelopPage.AddChild(CorePermissionNames.DevelopPage.Edit);
            DevelopPage.AddChild(CorePermissionNames.DevelopPage.Delete);
        }

        private static LocalizableString L(string name)
        {
            return LocalizableString.Create<SettingManagementResource>(name);
        }
    }
}
