//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 1.102.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Microsoft.EntityFrameworkCore;
using Volo.Abp;
namespace FS.Abp.SettingManagement.EntityFrameworkCore
{
    public static class SettingManagementDbContextModelCreatingExtensions
    {
        public static void ConfigureSettingManagement(
            this ModelBuilder builder,
            Action<SettingManagementModelBuilderConfigurationOptions> optionsAction = null)
        {
            Check.NotNull(builder, nameof(builder));

            var options = new SettingManagementModelBuilderConfigurationOptions(
                SettingManagementDbProperties.DbTablePrefix,
                SettingManagementDbProperties.DbSchema
            );

            optionsAction?.Invoke(options);

        }
    }
}
